name: 'Publish app to Google App Engine'
description: 'Publish app to Google App Engine'
author: 'Xiang Zheng'
inputs:
  service_account_email:
    description: 'The service account email which will be used for authentication.'
    required: true

  service_account_key:
    description: 'The service account key which will be used for authentication.'
    required: true

  client_secret_file:
    description: 'Optionaly choose where the service account .json file will be saved (defaults to ./client-secret.json).'
    required: false

  project_id:
    description: 'GAE project id'
    required: true

  gae_variables:
    description: 'GAE variables to be written to the app.yaml file'
    required: false

  gae_config_path:
    description: 'Path to the app.yml, Defaults to ./app.yml'
    required: false


runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'award'
  color: 'blue'
